<template>
  <div id="chat">
    <div
      class="p-0 showChat user-select-none"
      :class="{ hide: show }"
      @click="showChat(true)"
    >
      <img class="__icon" :src="img.chat" alt="loading gif" />
    </div>

    <div id="chatBox" :class="{ hide: !show }">
      <div class="p-2 d-flex flex-row justify-content-between">
        <span class="p-1">
          Team chat: <b>{{ playerTeam.name }}</b>
        </span>
        <div
          class="user-select-none cursor-pointer p-1 me-2"
          @click="showChat(false)"
        >
          X
        </div>
      </div>
      <div class="messages" ref="messages">
        <div
          class="messageBox"
          :class="[
            { sender: mess.username == playerName },
            { generic: mess.systemMsg },
          ]"
          v-for="mess in messages"
          :key="mess.timestamp"
        >
          <b :class="mess.role"
            >{{ mess.username }}{{ mess.systemMsg ? "" : ":" }}</b
          >
          {{ mess.text }}
          <div class="messageTimestamp">{{ mess.timestamp }}</div>
        </div>
      </div>
      <div class="input">
        <input
          placeholder="Enter message"
          v-model="message"
          v-on:keyup.enter="sendMessage"
        />
        <button v-on:click="sendMessage" id="sendMessage">
          <svg
            xml:space="preserve"
            viewBox="0 0 100 100"
            y="0"
            x="0"
            xmlns="http://www.w3.org/2000/svg"
            id="圖層_1"
            version="1.1"
            height="2.4rem"
            xmlns:xlink="http://www.w3.org/1999/xlink"
            style="
              width: 100%;
              height: 100%;
              background-size: initial;
              background-repeat-y: initial;
              background-repeat-x: initial;
              background-position-y: initial;
              background-position-x: initial;
              background-origin: initial;
              background-color: initial;
              background-clip: initial;
              background-attachment: initial;
              animation-play-state: paused;
            "
          >
            <g
              class="ldl-scale"
              style="
                transform-origin: 50% 50%;
                transform: rotate(0deg) scale(0.8, 0.8);
                animation-play-state: paused;
              "
            >
              <path
                d="M90 14.8v-.4-.2c0-.1-.1-.2-.1-.3v-.1l-.1-.1c-.1-.1-.1-.2-.2-.2-.1-.1-.1-.1-.2-.1l-.1-.1s-.1 0-.1-.1c-.1 0-.1-.1-.2-.1h-.5c-.1 0-.2 0-.3.1h-.1L10.9 45.9c-.5.2-.9.7-.9 1.3 0 .6.3 1.1.8 1.4l15.6 8.6c.2.1.5.2.7.2.3 0 .6-.1.8-.3l48-32.3-37.6 36.8c-.3.3-.4.7-.4 1.1v22.8c0 .6.4 1.2 1 1.4.2.1.3.1.5.1.5 0 .9-.2 1.2-.6l11.4-15 18.9 10.4c.4.2.9.2 1.3.1.4-.2.7-.5.8-1L90 15v-.2z"
                style="animation-play-state: paused"
              ></path>
            </g>
            <!-- generated by https://loading.io/ -->
          </svg>
        </button>
      </div>
    </div>
  </div>
</template>

<script>
import socket from "@/socket";

import config from "@/config.js";

export default {
  name: "Chat",
  data() {
    return {
      img: {
        chat: require("../assets/medias/chat-1.1s-200px.svg"),
      },
      messages: [],
      message: "",
      scrolledToBottom: true,
      show: true,
    };
  },
  computed: {
    connection() {
      return this.$store.state.SOCKET_connection;
    },
    gameId() {
      return this.$store.state.player.gameId;
    },
    playerName() {
      return this.$store.state.player.username;
    },
    playerRole() {
      return this.$store.state.player.role;
    },
    playerTeam() {
      return this.$store.state.player.team;
    },
  },
  methods: {
    sendMessage() {
      if (this.message == "") return;

      const message = {
        username: this.playerName,
        role: this.playerRole,
        timestamp: new Date().toUTCString(),
        text: this.message,
      };

      this.addMessageToStorage(message);

      socket.emit("chatMessage", this.message);

      this.message = "";
    },

    scrollToEnd() {
      var content = this.$refs.messages;
      if (content) {
        content.scrollTop = content.scrollHeight;
        this.scrolledToBottom = true;
      }
    },

    showChat(value) {
      this.show = value;
    },

    addMessageToStorage(msg) {
      this.messages.push(msg);
    },

    getTeamMessages() {
      fetch(
        `${config.gameApi.url}/server/chatMessages/${this.gameId}/${this.playerTeam.index}`,
        {
          method: "GET",
          headers: {
            Authorization: `Bearer ${this.$store.state.user.token}`,
          },
        }
      )
        .then(async (response) => {
          const data = await response.json();
          console.debug("Get Chat messages: ", data);
          this.messages = data.messages || [];
        })
        .catch((error) => {
          console.debug("Couldnt get chat messages");
          console.error(error);
        });
    },
  },

  beforeUpdate() {
    var content = this.$refs.messages;
    if (content) {
      this.scrolledToBottom =
        Math.abs(
          content.scrollHeight - content.clientHeight - content.scrollTop
        ) < 1;
    }
  },

  updated() {
    this.$nextTick(() => {
      if (this.scrolledToBottom) this.scrollToEnd();
    });
  },

  mounted() {
    this.scrollToEnd();
  },

  created() {
    console.debug("Chat component created");

    this.getTeamMessages();

    socket.on("chatMessage", (message) => {
      this.addMessageToStorage(message);
    });

    socket.on("chatAction", (event) => {
      let text;
      switch (event.action) {
        case "join":
          text = "Joined game";
          break;
        case "leave":
          text = "Left game";
          break;
        default:
          text = "Unsupported action";
      }

      const message = {
        systemMsg: true,
        username: event.player.username,
        role: event.player.role,
        timestamp: new Date().toUTCString(),
        text,
      };

      this.addMessageToStorage(message);

      console.debug("Player chat action", event.player);
    });
  },

  unmounted() {
    socket.off("chatMessage");
    socket.off("chatAction");
  },
};
</script>

<style lang="scss" scoped>
#chat {
  z-index: 15;
  min-height: 10rem;

  overflow: hidden;

  position: fixed;
  bottom: 0;
  right: 10px;

  padding: 15px;

  max-width: 100vw;

  @include media-breakpoint-down(sm) {
    & {
      //width: 30rem;
      bottom: 2rem;
      right: 5px;
    }
  }
}

#chatBox {
  min-width: 200px;
  height: 40rem;
  width: 30rem;
  max-width: 96vw;
  max-height: 70vh;

  border-radius: 1rem;
  background: white;

  -webkit-box-shadow: 0px 0px 12px -5px rgba(66, 68, 90, 1);
  -moz-box-shadow: 0px 0px 12px -5px rgba(66, 68, 90, 1);
  box-shadow: 0px 0px 12px -5px rgba(66, 68, 90, 1);

  display: flex;
  flex-direction: column;

  transition-duration: 0.2s;
  opacity: 1;

  &.hide {
    height: 0;
    opacity: 0;
  }
  .messages {
    background: #f7f7f7;
    height: 100%;
    flex-shrink: 2;
    overflow-y: auto;
    box-shadow: inset 0 2rem 2rem -2rem rgb(0 0 0 / 5%),
      inset 0 -2rem 2rem -2rem rgb(0 0 0 / 5%);
  }
  .input {
    flex-basis: 4rem;
    display: flex;
    align-items: center;
    padding: 0.5rem 0.5rem;
    input {
      border: none;
      background-image: none;
      background-color: white;
      padding: 0.5rem 1rem;
      border-radius: 1.125rem 0 0 1.125rem;
      flex-grow: 2;
      box-shadow: 0 0 1rem rgb(0 0 0 / 10%),
        0rem 1rem 1rem -1rem rgb(0 0 0 / 20%);
      font-family: Red hat Display, sans-serif;
      font-weight: 400;
      letter-spacing: 0.025em;
    }
  }
}

#sendMessage {
  padding: 0;
  padding-right: 5px;
  border-radius: 0 1.125rem 1.125rem 0;
}
.messageTimestamp {
  display: none;
  font-size: 80%;
  color: grey;
}

.messageBox {
  word-break: break-all;
  box-sizing: border-box;
  padding: 0.5rem 1rem;
  margin: 0.8rem;
  background: #fff;
  border-radius: 1.125rem 1.125rem 1.125rem 0;
  min-height: 2.25rem;
  width: -webkit-fit-content;
  width: -moz-fit-content;
  width: fit-content;
  max-width: 66%;
  box-shadow: 0 0 0.5rem rgb(0 0 0 / 8%), 0rem 1rem 1rem -1rem rgb(0 0 0 / 10%);
  &:hover .messageTimestamp {
    display: block;
  }
}
.sender {
  margin: 0.8rem 0.8rem 0.8rem auto;
  border-radius: 1.125rem 1.125rem 0 1.125rem;
}

.generic {
  text-align: center;
  margin: 0 auto;
  border: 0;
  background: none;
  color: grey;
  box-shadow: none;
  word-break: normal;
}

.showChat {
  opacity: 1;
  background: #fff;
  border-radius: 50%;

  bottom: 1rem;
  right: 15px;
  position: absolute;

  z-index: 15;
  &.hide {
    display: none;
  }

  .__icon {
    height: 5rem;
  }
}
</style>
